### ISSUE TITLE
Issue for App preview 

### ISSUE THREAD

**Issue by MinalGithub** [SAP-samples/teched2021-IIS160#3]
https://github.com/SAP-samples/teched2021-IIS160/blob/main/exercises/ex1/README.md
Exercise 1.3 Starting the App 

Getting issue for preview application. Not have any blocks message for sight . Try to update port 4005 as suggested, still getting same issue. please help.
[issue.docx](https://github.com/SAP-samples/teched2021-IIS160/files/7630844/issue.docx)
[issue.docx](https://github.com/SAP-samples/teched2021-IIS160/files/7630846/issue.docx)

**Comment by c-kobo** [comment]
Hi @MinalGithub ,

sorry for not responding more early, I must have missed the notification.
In the attached screenshot, in the terminal I can see  error message:
'cds watch' needs '@sap/cds-dk' to be installed.'
This node dependency needs to be installed globally wrt your dev space, and is required for the CDS compiler command line tools. If not installed, the service can't be launched by running cds watch.
Package @sap/cds-dk should be available per default for dev spaces that were created with profile 'Full Stack Cloud Application', as described in Exercise 0 step '[Creating the development space](https://github.com/SAP-samples/teched2021-IIS160/tree/main/exercises/ex0#creating-the-development-space)'.
Could you please recreate the dev space and make sure that the right profile was selected?
Alternatively, you can install the package in your existing dev space by running terminal command
npm i -g @sap/cds-dk

Please confirm whether this helps.

Best regards
Christian

![image](https://user-images.githubusercontent.com/39270906/147083035-7d6e7cf0-15be-4e78-be9f-b49fd993c54b.png)
