### ISSUE TITLE
Ex  5 step 8  issue and  Ex 7 Not found file ObjectPageExtension.controller.js 

### ISSUE THREAD

**Issue by MinalGithub** [SAP-samples/teched2021-IIS160#5]
Exercise 5 - Adding a Micro Chart to the Table Building Block
Exercise 5.2 Enhance UI.LineItem Annotation via Code Completion
not getting option for step 8 
[](https://github.com/SAP-samples/teched2021-IIS160/blob/main/exercises/ex5/images/fieldicon02.png)Trigger code completion by pressing ctrl+space and select icon 

How to add it  Or what actual code needs to be. 

[Exercise 7 - Flexible Programming Model: Changing the Edit Flow by Implementing a Controller Extension](https://github.com/SAP-samples/teched2021-IIS160/blob/main/exercises/ex7#exercise-7---flexible-programming-model-changing-the-edit-flow-by-implementing-a-controller-extension) 

Not found file ObjectPageExtension.controller.js  for below step 

Open project folder app/test-resources/ext.
Drag and drop file ObjectPageExtension.controller.js (5) to folder app/managetravels/webapp/ext (6).

**Comment by c-kobo** [comment]
Hello @MinalGithub ,

at first, please make sure that the CDS file is syntax error free.
Please trigger LSP support first and then type 'Anno' to filter results.
If that doesn't work for you, you can find the complete annotation snippet after step 10 and copy it from there.
For exercise 7, the file is located in folder app/test-resources/ext.
Here is the complete path:
https://github.com/SAP-samples/teched2021-IIS160/blob/main/app/test-resources/ext/ObjectPageExtension.controller.js
I hope that helps.
